name: Deploy App

on:
  workflow_dispatch: # Manual trigger without inputs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm nx build sapod-web

      - name: Deploy to Hostinger
        env:
          HOSTINGER_SFTP_HOST: ${{ secrets.HOSTINGER_SFTP_HOST }}
          HOSTINGER_SFTP_USER: ${{ secrets.HOSTINGER_SFTP_USER }}
          HOSTINGER_SFTP_PASSWORD: ${{ secrets.HOSTINGER_SFTP_PASSWORD }}
        run: |
          # Create a temporary script for deployment
          echo "
          mirror -R ./dist/apps/sapod-web/ /public_html/
          bye
          " > deploy.txt

          # Use lftp for more reliable SFTP transfer
          sudo apt-get install -y lftp
          lftp -e "set sftp:auto-confirm yes" \
               -u "$HOSTINGER_SFTP_USER","$HOSTINGER_SFTP_PASSWORD" \
               sftp://"$HOSTINGER_SFTP_HOST" \
               -f deploy.txt

          rm deploy.txt
