name: Deploy App

on:
  workflow_dispatch: # Manual trigger without inputs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the specified branch (main)
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'main'

      # Step 2: Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Step 3: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      # Step 4: Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install

      # Step 5: Build the Nx app (production build)
      - name: Build the sapod web app
        run: pnpm nx build sapod-web

      # Step 6: Deploy to Hostinger
      - name: Deploy to Hostinger
        env:
          HOSTINGER_SFTP_HOST: ${{ secrets.HOSTINGER_SFTP_HOST }}
          HOSTINGER_SFTP_USER: ${{ secrets.HOSTINGER_SFTP_USER }}
          HOSTINGER_SFTP_PASSWORD: ${{ secrets.HOSTINGER_SFTP_PASSWORD }}
        run: |
          curl -T ./dist/apps/sapod-web/* -u $HOSTINGER_SFTP_USER:$HOSTINGER_SFTP_PASSWORD sftp://$HOSTINGER_SFTP_HOST/your/path/to/public_html/
